/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.corto2.newpackage1;

import com.mycompany.corto2.newpackage.Auto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author zacap
 */
public class menu extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnauto = new javax.swing.JButton();
        btncamion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnauto.setText("Auto");
        getContentPane().add(btnauto);
        btnauto.setBounds(40, 30, 72, 23);

        btncamion.setText("Camion");
        btncamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncamionActionPerformed(evt);
            }
        });
        getContentPane().add(btncamion);
        btncamion.setBounds(150, 30, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncamionActionPerformed
        // TODO add your handling code here:
        Auto auto  = new Auto();
        auto.getAño(f);
        System.out.print(auto.getAño());
    }//GEN-LAST:event_btncamionActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnauto;
    private javax.swing.JButton btncamion;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
    
        if(e.getSource()==btnauto)
        {
            vistaAuto vista=new vistaAuto();
            vista.setBounds(100,100,400,400);
            vista.setVisible(true);
            
            
            
        }
    }
}
